### ISSUE TITLE
KiCat 7 fails with "DA_TEXT_GetEffectiveTextShape() takes no keyword arguments"

### ISSUE THREAD

**Issue by kaysievers** [openscopeproject/InteractiveHtmlBom#344] opened 2023-01-07 12:54 UTC
This happens with the Kicad 7.0 release candidate

<img width="547" alt="Screenshot 2023-01-07 at 13 51 57" src="https://user-images.githubusercontent.com/1064936/211151570-56e78396-2643-4c36-82e3-c1787deedcc2.png">

Thanks!

**Comment by qu1ck** [comment] 2023-01-08 00:59
Thanks for the report, this was caused by change in kicad that I fixed in https://gitlab.com/kicad/code/kicad/-/merge_requests/1437

Next nightly or rc should work fine.

**Closed by qu1ck** 2023-01-08 00:59 UTC

**Comment by kaysievers** [comment] 2023-01-08 10:21
It works again. Thanks!
