### ISSUE TITLE
Add Option to highlight on table hover or click

### ISSUE THREAD

**Issue by drid** [openscopeproject/InteractiveHtmlBom#194] opened 2020-10-09 20:16 UTC
Currently components are highlighted on PCB when mouse hovers over table row.
This can lead to errors if the mouse is used for other applications and moves around.
I personally change `tr.onmousemove` to `tr.onclick = handler;` but it would be even better to have an option about that

**Comment by qu1ck** [comment] 2020-10-09 20:50
Duplicate of #88 
There is a solution using custom js in the comments.

I'm not inclined to add an option because I want to avoid the option menu to become bloated. It's already large enough.

**Closed by qu1ck** 2020-10-09 20:50 UTC
